db_username       = "auroraserverless"      # Input Database username
db_password       = "Seyi1234"              # Input Database password
route53_zone_id   = "Z06639231JA5LVJ5MKIMA" # Input your public hosted zone Route53 ID
route53_zone_name = "giddychild.com"        # Input your Route53 Zone Name
keycloak_username = "admin"
keycloak_password = "Seyi1234"                                                                            # Input a password for accsessing Keycloak Server
cert_arn          = "arn:aws:acm:us-east-1:155125294186:certificate/b8efe1a4-392d-4889-9170-9314e86bf609" # Input your ACM Cert ARN
database_name     = "keycloakdemo"
environment       = "dev"
cluster_version   = "1.27"